### ISSUE TITLE
cursor disappears in code block under certain instances

### ISSUE THREAD

**Issue by audibleblink** [lazercaveman/Firefly-Obsidian-Theme#12]
I thought you may want to know that people using obsidian's core vim mode along with the [Editor Syntax Highlighting Plugin](https://github.com/deathau/cm-editor-syntax-highlight-obsidian) lose their cursor when navigating inside code blocks; the cursor blocks and the code background color match. This happens in both light and dark mode.

Probably a tiny cross-section of users, but thought I'd let you know anyway.

Wonderful theme, thank you!

**Comment by lazercaveman** [comment]
Thanks for letting me know, I'm working on the theme every now and then (more like on the side) and changing something when something bothers me. Basically syntax highlighting in code blocks is already a built-in feature in Obsidian, and firefly Theme will add its own syntax-highlighting flavour in the future. Anyways, when I get a chance I'll take a closer look at the problem. : )

I'm glad you like the theme - so thank you for thank you! : )

**Comment by lazercaveman** [comment]
Thank you once more for reaching out - I had a look at the plugin! : ) 

Since time is rare I will not work on that one - Obsidian already supports syntax highlighting within the document preview, hopefully they'll do so for the editor soon as well.
