### ISSUE TITLE
Way to decrease the font size?

### ISSUE THREAD

**Issue by kenjibailly** [lazercaveman/Firefly-Obsidian-Theme#20]
The font size slider in the settings doesn't seem to work nor ctrl+scroll.

Is there a way to decrease the size of the fonts?

**Comment by lazercaveman** [comment]
Command + Minus should do the job, Command + 0 to get back to normal again.

**Comment by kenjibailly** [comment]
I can make it bigger, I can reset it, but I can't make it smaller. I'm on windows. ctrl + minus doesn't do anything for me nor can I find it in the hotkeys. I tried every key on my keyboard asfaik right now. Is ctrl + 0 the minimum size? I can't seem to go under that. 

But to me everything looks pretty damn big 
![image](https://user-images.githubusercontent.com/9883910/149405921-60ded121-9b7a-4403-a08a-961bf3b4aef4.png)

**Comment by lazercaveman** [comment]
in Windows 10 I haven’t found a way to zoom-in / zoom-out like it’s possible in Mac OS. I think this is more of an Obsidian issue than a theme issue.
